import esbuild from 'esbuild';
import path from 'path';

const isProd = process.env.build === 'production';

const banner = `
/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

esbuild.build({
  banner: {
    js: banner,
  },
  entryPoints: ['main.ts'],
  bundle: true,
  format: 'cjs',
  target: 'es6',
  external: ['obsidian'],
  outfile: 'main.js',
  sourcemap: !isProd,
  minify: isProd,
  plugins: [
    {
      name: 'watch-plugin',
      setup: (build) => {
        build.onEnd((result) => {
          if (result.errors.length > 0) {
            console.log('Build failed:', result.errors);
          } else {
            console.log('Build complete');
          }
        });
      },
    },
  ],
});
