
/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);
var __async = (__this, __arguments, generator) => {
  return new Promise((resolve, reject) => {
    var fulfilled = (value) => {
      try {
        step(generator.next(value));
      } catch (e) {
        reject(e);
      }
    };
    var rejected = (value) => {
      try {
        step(generator.throw(value));
      } catch (e) {
        reject(e);
      }
    };
    var step = (x) => x.done ? resolve(x.value) : Promise.resolve(x.value).then(fulfilled, rejected);
    step((generator = generator.apply(__this, __arguments)).next());
  });
};

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => TagFilterPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var TagFilterPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.activeFilters = [];
    this.tagBarEl = null;
  }
  onload() {
    return __async(this, null, function* () {
      this.registerEvent(
        this.app.metadataCache.on("changed", (file) => {
          if (file instanceof import_obsidian.TFile)
            this.refreshTagBar();
        })
      );
      this.registerEvent(
        this.app.vault.on("create", (file) => __async(this, null, function* () {
          if (file instanceof import_obsidian.TFile) {
            yield this.addTagsToNewFile(file);
            this.refreshTagBar();
          }
        }))
      );
      this.registerEvent(
        this.app.vault.on("delete", (file) => {
          if (file instanceof import_obsidian.TFile)
            this.refreshTagBar();
        })
      );
      this.registerEvent(
        this.app.vault.on("rename", (file) => {
          if (file instanceof import_obsidian.TFile)
            this.refreshTagBar();
        })
      );
      this.app.workspace.onLayoutReady(() => {
        this.injectTagBar();
      });
    });
  }
  onunload() {
    var _a;
    (_a = this.tagBarEl) == null ? void 0 : _a.remove();
  }
  addTagsToNewFile(file) {
    return __async(this, null, function* () {
      if (this.activeFilters.length === 0)
        return;
      const includeTags = this.activeFilters.filter((f) => f.mode === "include").map((f) => `#${f.tag}`);
      if (includeTags.length === 0)
        return;
      const content = yield this.app.vault.read(file);
      yield this.app.vault.modify(file, includeTags.join(" ") + "\n\n" + content);
      new import_obsidian.Notice(`Added tags: ${includeTags.join(", ")}`);
    });
  }
  getActiveFilters() {
    return this.activeFilters;
  }
  setActiveFilters(filters) {
    this.activeFilters = filters;
    this.applyToFileExplorer();
    this.refreshTagBar();
  }
  injectTagBar() {
    const fileExplorerLeaf = this.app.workspace.getLeavesOfType("file-explorer")[0];
    if (!fileExplorerLeaf)
      return;
    const container = fileExplorerLeaf.view.containerEl;
    if (container.querySelector(".tag-filter-bar")) {
      this.tagBarEl = container.querySelector(".tag-filter-bar");
      return;
    }
    this.tagBarEl = container.createDiv("tag-filter-bar");
    const navHeader = container.querySelector(".nav-header");
    if (navHeader) {
      navHeader.after(this.tagBarEl);
    } else {
      container.prepend(this.tagBarEl);
    }
    this.renderTagBar();
  }
  renderTagBar() {
    if (!this.tagBarEl)
      return;
    this.tagBarEl.empty();
    const tagMap = this.getAllTags();
    const validFilters = this.activeFilters.filter((f) => tagMap.has(f.tag));
    if (validFilters.length !== this.activeFilters.length) {
      this.activeFilters = validFilters;
      this.applyToFileExplorer();
    }
    const tags = Array.from(tagMap.entries());
    tags.sort((a, b) => a[0].localeCompare(b[0]));
    const header = this.tagBarEl.createDiv("tag-filter-header");
    header.createSpan({ text: "\u{1F3F7}\uFE0F Filter:" });
    const clearButton = header.createEl("button", { text: "Clear All" });
    clearButton.addClass("tag-filter-clear-btn");
    clearButton.onclick = () => {
      this.activeFilters = [];
      this.applyToFileExplorer();
      this.renderTagBar();
    };
    const tagList = this.tagBarEl.createDiv("tag-filter-list");
    for (const [tag] of tags) {
      const tagButton = tagList.createDiv("tag-filter-button");
      const filterState = this.activeFilters.find((f) => f.tag === tag);
      if (filterState) {
        tagButton.addClass(filterState.mode === "include" ? "include" : "exclude");
      }
      tagButton.createSpan("tag-text").textContent = `#${tag}`;
      tagButton.onclick = () => this.cycleTagFilter(tag);
    }
    if (tags.length === 0) {
      tagList.createDiv("tag-filter-empty").textContent = "No tags found";
    }
    const fileListContainer = this.tagBarEl.createDiv("tag-filter-file-list-container");
    this.renderFileList(fileListContainer);
  }
  matchesFilters(file) {
    const cache = this.app.metadataCache.getFileCache(file);
    const fileTags = /* @__PURE__ */ new Set();
    if (cache == null ? void 0 : cache.tags) {
      for (const tag of cache.tags) {
        fileTags.add(tag.tag.startsWith("#") ? tag.tag.slice(1) : tag.tag);
      }
    }
    for (const filter of this.activeFilters) {
      const hasTag = fileTags.has(filter.tag);
      if (filter.mode === "include" && !hasTag)
        return false;
      if (filter.mode === "exclude" && hasTag)
        return false;
    }
    return true;
  }
  getFilteredFiles() {
    if (this.activeFilters.length === 0)
      return [];
    return this.app.vault.getMarkdownFiles().filter((f) => this.matchesFilters(f));
  }
  renderFileList(container) {
    var _a, _b;
    container.empty();
    if (this.activeFilters.length === 0)
      return;
    const filteredFiles = this.getFilteredFiles();
    const header = container.createDiv("tag-filter-file-list-header");
    header.createSpan({ text: `\u{1F4C4} Results (${filteredFiles.length})` });
    const fileList = container.createDiv("tag-filter-file-list");
    if (filteredFiles.length === 0) {
      fileList.createDiv("tag-filter-file-empty").textContent = "No files match the current filters";
      return;
    }
    for (const file of filteredFiles) {
      const fileItem = fileList.createDiv("tag-filter-file-item");
      const fileLink = fileItem.createEl("a", { text: file.basename, href: "#" });
      fileLink.addClass("tag-filter-file-link");
      fileLink.onclick = (e) => {
        e.preventDefault();
        this.app.workspace.openLinkText(file.path, "", false);
      };
      if (((_a = file.parent) == null ? void 0 : _a.name) !== "/") {
        fileItem.createDiv("tag-filter-file-path").textContent = ((_b = file.parent) == null ? void 0 : _b.name) || "";
      }
    }
  }
  getAllTags() {
    const tagMap = /* @__PURE__ */ new Map();
    for (const file of this.app.vault.getMarkdownFiles()) {
      const cache = this.app.metadataCache.getFileCache(file);
      if (cache == null ? void 0 : cache.tags) {
        for (const tag of cache.tags) {
          const tagName = tag.tag.startsWith("#") ? tag.tag.slice(1) : tag.tag;
          tagMap.set(tagName, (tagMap.get(tagName) || 0) + 1);
        }
      }
    }
    return tagMap;
  }
  cycleTagFilter(tag) {
    const filters = this.activeFilters;
    const currentIndex = filters.findIndex((f) => f.tag === tag);
    if (currentIndex === -1) {
      filters.push({ tag, mode: "include" });
    } else if (filters[currentIndex].mode === "include") {
      filters[currentIndex].mode = "exclude";
    } else {
      filters.splice(currentIndex, 1);
    }
    this.setActiveFilters(filters);
  }
  applyToFileExplorer() {
    const fileExplorerLeaf = this.app.workspace.getLeavesOfType("file-explorer")[0];
    if (!fileExplorerLeaf)
      return;
    const container = fileExplorerLeaf.view.containerEl;
    const allFiles = this.app.vault.getMarkdownFiles();
    const filteredPaths = new Set(allFiles.filter((f) => this.matchesFilters(f)).map((f) => f.path));
    container.querySelectorAll(".nav-file").forEach((item) => {
      var _a;
      const htmlItem = item;
      const path = (_a = htmlItem.file) == null ? void 0 : _a.path;
      if (path) {
        const visible = this.activeFilters.length === 0 || filteredPaths.has(path);
        htmlItem.style.display = visible ? "" : "none";
        htmlItem.toggleClass("is-filtered-out", !visible);
      }
    });
    container.querySelectorAll(".nav-folder-contents").forEach((folder) => {
      const htmlFolder = folder;
      const hasVisible = Array.from(
        htmlFolder.querySelectorAll(":scope > .nav-file, :scope > .nav-folder")
      ).some((child) => child.style.display !== "none");
      htmlFolder.style.display = hasVisible ? "" : "none";
    });
    this.updateStatus(filteredPaths.size, allFiles.length);
  }
  updateStatus(shown, total) {
    var _a;
    let statusEl = (_a = this.tagBarEl) == null ? void 0 : _a.querySelector(".tag-filter-status");
    if (!statusEl && this.tagBarEl) {
      statusEl = this.tagBarEl.createDiv("tag-filter-status");
    }
    if (statusEl) {
      if (this.activeFilters.length > 0) {
        statusEl.textContent = `Showing ${shown} of ${total} files`;
        statusEl.addClass("active");
      } else {
        statusEl.removeClass("active");
        statusEl.textContent = "";
      }
    }
  }
  refreshTagBar() {
    this.renderTagBar();
  }
};
//# sourceMappingURL=main.js.map
